# Generated by Django 5.0.3 on 2024-03-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_cuerso_entregable_profesor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuerso',
            new_name='Curso',
        ),
    ]
